### ISSUE TITLE
Read only HOME directory does not work in OpenShift

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/docker-invenio#17]
The assumption of a writable directory done by ``pipenv`` does not work in OpenShift or other deplyments that have no or at least non writable home directories.

There is an official ``pipenv`` ticket [here](https://github.com/pypa/pipenv/issues/2195).

I opted for the same solution and added to my Dockerfile the following ENV variables:

```docker
ENV PIPENV_VENV_IN_PROJECT="/opt/invenio/src/"
ENV PIPENV_CACHE_DIR="/opt/invenio/src/"
```

However, since ``pipenv`` is installed here it might be nice to add those lines and make it match with the ``WORKING_DIR``.

**Comment by Glignos** [comment]
As discussed IRL with @slint:
Since we are already in the context of a container there doesn't seem to be a need for more isolation using virtualenv's.

A good fix for this issue is running `pipenv` with the use of the `--system` parameter at the image's build time to install the dependencies systemwide.
This should fix any reading permission issue with the working user.

There should also be mentioned that it's safer to change the user at the very end of the Dockerfile after the needed permission(`chown`) and user group modifications(`chgrp`), to avoid any permission issues.
